#pragma config(Sensor, port2,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port3,  colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Sensor, port4,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  distanceMM,     sensorVexIQ_Distance)
#pragma config(Sensor, port8,  bumpSwitch,     sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	repeat (25) {
		setTouchLEDColor(touchLED, colorNone);
		if (getColorHue(colorDetector) < 20) {
			displaySensorValues(line1, colorDetector);
			// Set the LED to Red
			// Red detector (red is < 20)
			setTouchLEDColor(touchLED, colorRed);
			wait(5, seconds);
			playSound(soundTada);
			setTouchLEDColor(touchLED, colorLimeGreen);
		}
		if (getColorHue(colorDetector) > 100) {
			// Set the LED to Blue
			// Blue detector (blue is > 100) 
			displaySensorValues(line1, colorDetector);
			setTouchLEDColor(touchLED, colorBlue);
			wait(5, seconds);
			playSound(soundTada);
			setTouchLEDColor(touchLED, colorLimeGreen);
		}
		// Play sound
		wait(4, seconds);
		playSound(soundRatchet4);
	}
}
