#pragma config(Sensor, port2,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port3,  colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Sensor, port4,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  distanceMM,     sensorVexIQ_Distance)
#pragma config(Sensor, port8,  bumpSwitch,     sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	// Assignment #1 Accelerate
	//// Acceleration
	repeat (4) {
		forward(90, degrees, 00);
	}
	repeat (4) {
		forward(90, degrees, 10);
	}
	repeat (4) {
		forward(90, degrees, 20);
	}
	repeat (4) {
		forward(90, degrees, 30);
	}
	repeat (4) {
		forward(90, degrees, 40);
	}
	repeat (4) {
		forward(90, degrees, 50);
	}
	repeat (4) {
		forward(90, degrees, 60);
	}
	repeat (4) {
		forward(90, degrees, 70);
	}
	repeat (4) {
		forward(90, degrees, 80);
	}
	repeat (4) {
		forward(90, degrees, 90);
	}
	repeat (4) {
		forward(90, degrees, 100);
	}
	playSound(soundSiren2);
	// Deceleration
	repeat (1) {
		forward(90, degrees, 90);
	}
	repeat (1) {
		forward(90, degrees, 80);
	}
	repeat (1) {
		forward(90, degrees, 70);
	}
	repeat (1) {
		forward(90, degrees, 60);
	}
	repeat (1) {
		forward(90, degrees, 50);
	}
	repeat (1) {
		forward(90, degrees, 40);
	}
	repeat (1) {
		forward(90, degrees, 30);
	}
	repeat (1) {
		forward(90, degrees, 20);
	}
	repeat (1) {
		forward(90, degrees, 10);
	}
	repeat (1) {
		forward(90, degrees, 00);
	}
	playSound(soundTada);
}
