#pragma config(Sensor, port2,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port3,  colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Sensor, port4,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  distanceMM,     sensorVexIQ_Distance)
#pragma config(Sensor, port8,  bumpSwitch,     sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	resetGyro(gyroSensor);
	resetMotorEncoder(armMotor);
	// Lift up the arm and claw
	moveMotor(clawMotor, -50, degrees, 50);
	moveMotor(armMotor, 500, degrees, 80);
	// Begin forward movement at half speed
	// Poll for the bump value while moving & stop when true
	repeatUntil (getBumperValue(bumpSwitch) == true) {
		forward(1.45, rotations, 75);
	}
	// Move backwards
	backward(.67, rotations, 25);
	moveMotor(armMotor, -499, degrees, 25);
	forward(.20, rotations, 25);
	// Other colors
	if (getColorHue(colorDetector) > 60) {
		if (getColorHue(colorDetector) < 100) {
			// Set the LED to Green
			wait(2, seconds);
			setTouchLEDColor(touchLED, colorGreen);
			moveMotor(clawMotor, 90, degrees, 100);
			moveMotor(armMotor, 500, degrees, 25);
			wait(1, seconds);
			turnRight(1.5, rotations, 50);
			// Polling for bump sequence
			repeatUntil (getBumperValue(bumpSwitch) == true) {
				forward(1, rotations, 50);
			}
			// Move backward
			backward(1.5, rotations, 50);
			// Manipulate arm and claw motor
			moveMotor(armMotor, -480, degrees, 100);
			moveMotor(clawMotor, -100, degrees, 100);
			moveMotor(armMotor, 250, degrees, 50);
			// Push block against wall
			forward(1.50, rotations, 50);
			// Move backward 1 rotation
			backward(1.55, rotations, 100);
			// Turning right
			turnRight(1.4, rotations, 100);
			// Moving forward
			forward(0.50, rotations, 50);
		}
	}
	if (getColorHue(colorDetector) > 180) {
		// Set the LED to Green
		wait(2, seconds);
		setTouchLEDColor(touchLED, colorGreen);
		moveMotor(clawMotor, 90, degrees, 100);
		forward(.50, rotations, 50);
		backward(1, rotations, 50);
		moveMotor(armMotor, 500, degrees, 25);
		wait(1, seconds);
		turnRight(1.50, rotations, 50);
		// Polling for bump sequence
		repeatUntil (getBumperValue(bumpSwitch) == true) {
			forward(1, rotations, 50);
		}
		// Move backward
		backward(1.5, rotations, 50);
		// Manipulate arm and claw motor
		moveMotor(armMotor, -480, degrees, 100);
		moveMotor(clawMotor, -100, degrees, 100);
		moveMotor(armMotor, 250, degrees, 50);
		// Push block against wall
		forward(1.5, rotations, 50);
		// Move backward
		backward(1.55, rotations, 100);
		// Turning right
		turnRight(1.4, rotations, 100);
		// Moving forward
		forward(0.5, rotations, 50);
	}
	// Blue detector (blue is above 100) 
	if (getColorHue(colorDetector) >= 100) {
		if (getColorHue(colorDetector) < 180) {
			// Set the LED to Blue
			wait(2, seconds);
			setTouchLEDColor(touchLED, colorBlue);
			moveMotor(clawMotor, 90, degrees, 100);
			forward(.50, rotations, 50);
			backward(.75, rotations, 50);
			moveMotor(armMotor, 500, degrees, 25);
			wait(1, seconds);
			turnLeft(0.70, rotations, 50);
			// Polling for bump sequence
			repeatUntil (getBumperValue(bumpSwitch) == true) {
				forward(1, rotations, 50);
			}
			// Move backward 1 rotation
			backward(1.5, rotations, 50);
			// Manipulate arm and claw motor
			moveMotor(armMotor, -480, degrees, 100);
			moveMotor(clawMotor, -100, degrees, 100);
			moveMotor(armMotor, 250, degrees, 50);
			// Push block against wall
			forward(1.50, rotations, 50);
			// Move backward 1 rotation
			backward(1.55, rotations, 100);
			// Turning right
			turnLeft(0.72, rotations, 50);
			// Moving forward
			forward(1.0, rotations, 50);
			turnRight(1.4, rotations, 50);
		}
	}
	// Red detector (red is 0)
	if (getColorHue(colorDetector) <= 30) {
		// Set the LED to Red
		wait(2, seconds);
		setTouchLEDColor(touchLED, colorRed);
		moveMotor(clawMotor, 90, degrees, 100);
		forward(.50, rotations, 50);
		backward(1, rotations, 50);
		moveMotor(armMotor, 500, degrees, 25);
		wait(1, seconds);
		turnRight(0.70, rotations, 50);
		// Polling for bump sequence
		repeatUntil (getBumperValue(bumpSwitch) == true) {
			forward(1, rotations, 50);
		}
		// Move backward 1 rotation
		backward(1.5, rotations, 50);
		// Manipulate arm and claw motor
		moveMotor(armMotor, -480, degrees, 100);
		moveMotor(clawMotor, -100, degrees, 100);
		moveMotor(armMotor, 250, degrees, 50);
		// Push block against wall
		forward(1.50, rotations, 50);
		// Move backward 1 rotation
		backward(1.55, rotations, 100);
		// Turning right
		turnRight(0.72, rotations, 100);
		// Moving forward
		forward(1.0, rotations, 50);
		turnLeft(1.4, rotations, 50);
	}
	// Play sound
	playSound(soundTada);
	stopAllMotors();
}
