myVariable = 0

def when_started1():
    global myVariable
    drivetrain.set_drive_velocity(100, PERCENT)
    drivetrain.turn_to_heading(270, DEGREES)
    drivetrain.drive_for(FORWARD, 800, MM)
    drivetrain.turn_to_heading(180, DEGREES)
    drivetrain.drive_for(FORWARD, 500, MM)
    drivetrain.turn_to_heading(0, DEGREES)
    brain.set_print_color(BLACK)
    pen.set_pen_color_rgb(0, 0, 0, 100)
    pen.fill(0, 0, 0, 100)
    pen.set_pen_width(MEDIUM)
    pen.move(DOWN)
    drivetrain.drive_for(FORWARD, 1200, MM)
    drivetrain.turn_to_heading(90, DEGREES)
    drivetrain.drive_for(FORWARD, 200, MM)
    drivetrain.set_drive_velocity(50, PERCENT)
    for repeat_count in range(75):
        drivetrain.drive(FORWARD)
        drivetrain.drive(FORWARD)
        drivetrain.turn(RIGHT)
        wait(5, MSEC)
    pen.move(UP)
    drivetrain.set_drive_velocity(100, PERCENT)
    drivetrain.turn_to_heading(135, DEGREES)
    drivetrain.drive_for(FORWARD, 400, MM)
    pen.move(DOWN)
    drivetrain.turn_to_heading(155, DEGREES)
    drivetrain.set_drive_velocity(50, PERCENT)
    drivetrain.drive_for(FORWARD, 375, MM)
    drivetrain.turn_to_heading(20, DEGREES)
    drivetrain.drive_for(FORWARD, 200, MM)
    drivetrain.turn_to_heading(155, DEGREES)
    drivetrain.drive_for(FORWARD, 200, MM)
    drivetrain.turn_to_heading(20, DEGREES)
    drivetrain.drive_for(FORWARD, 350, MM)
    pen.move(UP)
    drivetrain.set_drive_velocity(100, PERCENT)
    drivetrain.turn_to_heading(100, DEGREES)
    drivetrain.drive_for(FORWARD, 400, MM)
    drivetrain.turn_to_heading(0, DEGREES)
    pen.move(DOWN)
    drivetrain.set_drive_velocity(15, PERCENT)
    for repeat_count2 in range(85):
        drivetrain.drive(FORWARD)
        drivetrain.drive(FORWARD)
        drivetrain.turn(LEFT)
        wait(5, MSEC)
    drivetrain.drive_for(FORWARD, 75, MM)
    for repeat_count3 in range(85):
        drivetrain.drive(FORWARD)
        drivetrain.drive(FORWARD)
        drivetrain.turn(RIGHT)
        wait(5, MSEC)
    pen.move(UP)
    drivetrain.turn_to_heading(200, DEGREES)
    drivetrain.drive_for(FORWARD, 300, MM)
    drivetrain.turn_to_heading(0, DEGREES)
    stop_project()

vr_thread(when_started1)
